// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Movie struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	URL         string `json:"url"`
	ReleaseDate string `json:"releaseDate"`
}

type MovieFilter struct {
	Title       *string `json:"title,omitempty"`
	ReleaseDate *string `json:"releaseDate,omitempty"`
}

type MovieInput struct {
	Title       string `json:"title"`
	URL         string `json:"url"`
	ReleaseDate string `json:"releaseDate"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
}

type UserFilter struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type UserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
